# Generated by Django 2.2 on 2019-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
