# Generated by Django 2.2 on 2019-06-06 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_of_write',
            new_name='date_of_created',
        ),
        migrations.AddField(
            model_name='post',
            name='date_of_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
