# Generated by Django 2.2 on 2019-06-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190606_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='contents',
        ),
    ]
