# Generated by Django 2.2 on 2019-06-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190606_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_of_modified', 'date_of_created']},
        ),
    ]
