# Generated by Django 2.2 on 2019-06-14 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20190614_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_of_created', 'date_of_modified']},
        ),
    ]
