# Generated by Django 2.2 on 2019-06-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20190614_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_of_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_of_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
